### ISSUE TITLE
[FEATURE] Select between local or international flights

### ISSUE THREAD

**Issue by vivrelavie** [vivrelavie/FLIGHT-RESERVATION#62]
## Describe the feature

**Suggested by Ma'am Joms:** 
- Categorize if the user wants to select a local or an international flight.
- Edit SQL query to select only local or international flights.

### Files

Create new user control that will be displayed in the main panel. This will be showed before selecting flights.

### Expected behavior

1. User clicks Book Flight
2. Main panel displays the user control for local or international flight
3. User clicks continue
4. Main panel displays the flight booking user control 

### Additional Context
Change the 'Flight Bookings' label on sidebar and header to 'Book a Flight' or 'Book Flight'

## Tasks

- [ ] Change Flight booking label in sidebar and header
- [ ] Create User control for feature
- [ ] Create SQL query based on the user's choice (local or international)
- [ ] Display the query results to the flight selection
