### ISSUE TITLE
[FEATURE] Dashboard will show available flights

### ISSUE THREAD

**Issue by vivrelavie** [vivrelavie/FLIGHT-RESERVATION#63]
## Describe the feature

**Suggested by Ma'am Joms:** 
- Display the available flights in the dashboard

**Optional:**
- **Filter between the ff.** 
  - All flights available
  - Local
  - International
 ---

### Files

- dashboard.cs

### Expected behavior

1. User opens dashboard
2. Dashboard displays all flights available
3. User can select filters for all, local, or international flights available 

### Additional Context
Ma'am Joms recommended that the program should show the available flights even if they aren't logged in. To solve this, it is suggested to show the available flights in the dashboard.

## Tasks

- [x] Create SQL query that shows all the available flights.
- [x] Change the dashboard content to show the available flights. Format similar to view bookings.
- [x] Optional: Create a local or international filter.

**Comment by vivrelavie** [comment]
## New Tasks
- [ ] Make async.
- [ ] Remove QuerySelect from constructor.
